### PR TITLE
Need thumbs-up on CC0 LICENSE file from all contributors

### PR DESCRIPTION
**Pull request by JoshData**
Hi everyone who's contributed to this repo so far.

@tmcw set [`"license": "Public Domain"` in `package.json`](https://github.com/openlawdc/simple-generator/blob/master/package.json#L17), but we should make this more legally sound by adding a CC0 LICENSE file and a CONTRIBUTING.md file.

@tmcw: Does that sound ok to you?

If so, we need all contributors to sign-off on applying the CC0 waiver (see LICENSE in this commit) to their contributions:

- [x] @tmcw 
- [x] @vzvenyach 
- [x] @konklone 
- [x] @joshdata
- [x] @louh 

Indicate your sign-off by a :+1: please.

I hereby sign-off.

### CODE REVIEW

**Comment by konklone** [comment]
:+1:

**Comment by tmcw** [comment]
Yep, cool with me.

**Comment by louh** [comment]
:+1: :page_with_curl: :accept:

**Comment by JoshData** [comment]
Dave is on vacation, so I guess we'll wrap this up next week.

**Comment by vzvenyach** [comment]
@JoshData :100:

**Pull request merged**
